load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "get_diag.so",
    srcs = ["get_diag.cc"],
    gpu_srcs = ["get_diag.cu.cc"],
)

tf_custom_op_library(
    name = "gpu_cholesky.so",
    srcs = ["gpu_cholesky.cc", '/usr/local/cuda-7.5/lib64/libcusolver.so'],
    gpu_srcs = ["gpu_cholesky.cu.cc"],
)

tf_custom_op_library(
    name = "get_diag.so",
    srcs = ["get_diag.cc"],
    gpu_srcs = ["get_diag.cu.cc"],
)

tf_custom_op_library(
    name = "get_diag.so",
    srcs = ["get_diag.cc"],
    gpu_srcs = ["get_diag.cu.cc"],
)

